### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by copper73** [Exunys/Aimbot-V2#4]
[Aimbot-V2-main.zip](https://github.com/Exunys/Aimbot-V2/files/8312819/Aimbot-V2-main.zip)

**Comment by Exunys** [comment]
You need to download & install a script executor first. A supported, recommended, safe & trusted one is [Synapse X](https://x.synapse.to). Then you will copy the script from [Main.lua](https://github.com/Exunys/Aimbot-V2/blob/main/Resources/Scripts/Main.lua) and paste it into your executor and use it. The types of tickets I take & give support for is not these types of tickets, I will only accept glitches / bugs or feature requests. Thank you for your understanding.

**Comment by YBT762** [comment]
Can I use this on cronuszen or no ?

**Comment by YBT762** [comment]
Can I paste this in the cronuszen and will it work ?
